### ISSUE TITLE
Plan FAIR Search module

### ISSUE THREAD

**Issue by raar1** [fair-workflows/FAIRWorkbench#3]
This component of the workbench must search for existing input datasets, workflows (or potentially steps of workflows) and results of workflows, based on the RDF metadata annotating each. It appears that this search functionality is not considered to be a part of the FDP spec and therefore must be a separate module, although in principle it could be used alongside a given FDP.

So far we have considered a number of existing (but often dead or seemingly unmaintained) semantic search projects:
[https://www.openarchives.org/service/listproviders.html](https://www.openarchives.org/service/listproviders.html)

Google's dataset search ([https://datasetsearch.research.google.com/](https://datasetsearch.research.google.com/)) also exists but not clear if we'd have much control of anything.

Alternatively, upgrading the search capabilities of the nanopublishing prototype could be an option.

**Comment by bakhshir** [comment]
Carlos used the term "context aware search".
